ORDER_MOVIES = """
	SELECT MOVIES.NAME
	FROM MOVIES
	ORDER BY MOVIES.RATING;
"""
PRINT_FOR_DATE = """
	SELECT MOVIES.NAME
	FROM PROJECTIONS
	JOIN MOVIES
	ON MOVIES.ID = PROJECTIONS.MOVIE_ID 
	WHERE PROJECTIONS.DATE = {0}; # cursor.execute(PRINT_FOR_DATE.format(#promenliva za datata ot funciqta)
"""
SHOW_MOVIES_BY_ID = """
	SELECT MOVIES.ID, MOVIES.NAME
	FROM MOVIES
"""
