TAKE_USER_AMOUNT = """	
	SELECT COUNT(USERNAMES)
	FROM USER;
"""

TAKE_USER_NAME = """
	SELECT USERNAME
	FROM USER;
"""
TAKE_USER_PASSWORD = """
	SELECT PASSWORD
	FROM USER;
"""

GET_USERNAME_AND_PASSWORD = """
SELECT *
FROM users
WHERE username = ? and password = ?;"""
